apiVersion: v1
kind: Namespace
metadata:
  name: pooji-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pooji-flask-deployment
  namespace: pooji-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-calculator
  template:
    metadata:
      labels:
        app: flask-calculator
    spec:
      containers:
      - name: flask-calculator-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: "flask-test"
        - name: APP_NAME
          value: "flask-calculator"
        - name: LOG_LEVEL
          value: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: poojitha-flask-service
  namespace: pooji-ns
spec:
  selector:
    app: flask-calculator  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
